description = "sast link's example configuration"

[postgres]
username = "sastlink"
password = "sastlink"
host = "postgres"
dbname = "sastlink"
port = 5432

[redis]
host = "redis"
port = 6379
password = "sastlink"
db = 0

[jwt]
signing_key = "650be11c-bf2a-46e9-9620-13efb77a0378"

[log]
level = "debug"

[email]
sender = "xxxxx"
secret = "xxxxx"

[cos]
secret_id="xxx"
secret_key="xxx"

[oauth.server]
# urlExample := "postgres://username:password@localhost:5432/database_name"
db_uri = "postgres://sastlink:sastlink@postgres:5432/sastlink"
front_url = "http://localhost:3000"

[oauth.client.lark]
id = "xxx"
secret = "xxx"
redirect_url = "xxx"

[oauth.client.github]
id = "xxx"
secret = "xxx"
redirect_url = "xxx"
