description = "xxx's development configuration"

[database]
username = "xxxxx"
password = "xxxxx"
host = "xxxxx"
dbname = "link"
port = xxxx

[redis]
host = "xxx"
port = "11451"
password = "xxxxx"
db = "0"

[jwt]
signing_key = "xxxxx"

[log]
level = "debug"
