description = "sast link's development configuration"

[postgres]
username = "xxxxx"
password = "xxxxx"
host = "xxxxx"
dbname = "link"
port = 1234

[redis]
host = "xxx"
port = 11451
password = "xxxxx"
db = 0

[jwt]
signing_key = "xxxxx"

[log]
level = "debug"

[email]
sender = "xxxxx"
secret = "xxxxx"

[oauth]
# urlExample := "postgres://username:password@localhost:5432/database_name"
db_uri = "xxxx"
front_url = "http://localhost:3000"
