description = "sast link's development configuration"

[postgres]
username = "xxxxx"
password = "xxxxx"
host = "xxxxx"
dbname = "link"
port = 1234

[redis]
host = "xxx"
port = 11451
password = "xxxxx"
db = 0

[jwt]
signing_key = "xxxxx"

[log]
level = "debug"

[email]
sender = "xxxxx"
secret = "xxxxx"

[cos]
secret_id="xxx"
secret_key="xxx"

[oauth.server]
# urlExample := "postgres://username:password@localhost:5432/database_name"
db_uri = "xxxx"
front_url = "http://localhost:3000"

[oauth.client.lark]
id = "xxx"
secret = "xxx"
redirect_url = "xxx"

[oauth.client.github]
id = "xxx"
secret = "xxx"
redirect_url = "xxx"
